---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.3.91"
    vcenter_user: "administrator@group6.local"
    vcenter_pass: "Champlain123!"
    datacenter_name: "Group6-Datacenter"
    cluster_name: "Group 6 Cluster"
  tasks:
  - name: Creating Windows VM via Template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: DC01-CHEN
      template: ansible-template
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "SYS350-LUN06"
      state: poweredon
      wait_for_ip_address: yes
